CREATE TABLE user
(
    id       INTEGER PRIMARY KEY  AUTOINCREMENT NOT NULL ,
    rolle    TEXT,
    username VARCHAR(255),
    password VARCHAR(255)
);

CREATE TABLE wort
(
    id   INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    name VARCHAR(255) NULL
);