spring:
  security:
  session:
    jdbc:
      initialize-schema: always
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: "jdbc:sqlite:Linguo.sqlite"
    driver-class-name: org.sqlite.JDBC
    hikari:
      jdbc-url: "jdbc:sqlite:Linguo.sqlite"
  docker:
    compose:
      enabled: false
